def gv

pipeline{
    agent any
    stages {
        stage("copy files to ansible server"){
            steps{
                script{
                    echo "copying files all necessary files"
                }
            }
        }
    }
}