//CODE_CHANGES = getGitChange()
pipeline {
    agent any
    environment{
        NEW_VERSION = '1.2.1'
        CRED = credentials('credentialsID') // for using credentials from jenkins server
    }
    parameters{
        string(name: 'Version', defaultValue:'', description: 'version to deploy on prod')
        choice(name: 'Version', choices:['1.2.1','1.2.3'],description:'')
        booleanParam(name: 'executeTests', defaultValue: true, description:'')
    }
    stages {
        stage("build"){
            when {
                expression {
                    //CODE_CHANGES ==true
                }
            }
            steps{
                echo "building app"
                echo "building version ${NEW_VERSION}"
            }
        }

        stage("test"){
            when{
                expression {
                    params.executeTests //== true
                }
            }
            steps{
                echo "testing app ...."
            }
        }

         stage("deploy"){
            steps{
                echo "deploying app with ${parms.Version}"
                echo "deploying with ${CRED}"
                sh "${CRED}"
                // or directly apply here
                // withCredentials([
                //     usernamePassword(credentials: 'server-cred-id', usernameVar: USER, userPasswordVar: PWD)
                // ]){
                //     sh "some script ${USER} ${PWD}"
                // }
            }
    }
}

post {
    always{
        //
    }
    success{
        //
    }
    failure{
        //
    }
}
